services:
  - type: web
    name: memo-generator-backend
    env: node
    buildCommand: |
      npm install
      pip3 install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
