services:
  - type: web
    name: memo-generator-backend
    env: node
    plan: starter
    buildCommand: |
      npm install &&
      python3 -m pip install --user -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: backend
