services:
  - type: web
    name: memo-generator-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: EXA_API_KEY
        sync: false
      - key: PROXYCURL_API_KEY
        sync: false
      - key: PORTKEY_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
